[package]
name = "counting_elements_solution"
version = "0.1.0"
authors = ["VictorDuranEM <victor.duran.em@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
